# Generated by Django 6.0.2 on 2026-03-07 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA CHAI'), ('GR', 'GINGER CHAI'), ('KI', 'KIWI CHAI'), ('PL', 'PLAIN CHAI'), ('EL', 'ELAICHI CHAI')], max_length=2)),
            ],
        ),
    ]
